name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  
  build:
   
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run:  docker build -t andregondo/docker-resume-a . 

      - name: Push image 
        run: |
            docker login -u andregondo -p ${{secrets.REGISTRY_PASS}}
            docker push andregondo -p fafaff
            docker push andregondo/docker-resume-a
