name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  
  build:
   
    runs-on: ubuntu-${{ env.IMAGE_TAG }} 
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: |
          TAG=${GITHUB_SHA::8} # first 8 chars of commit SHA
            docker build --no-cache -t ${{secrets.REGISTRY_USERNAME}}/docker-resume-a:$TAG .
      - name: Push image 
        run: |
            docker login -u ${{secrets.REGISTRY_USERNAME}} -p ${{secrets.REGISTRY_PASS}}
            docker push ${{secrets.REGISTRY_USERNAME}}/docker-resume-a:$TAG
            echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV
      - name: Setup SSH
        run: |
          echo "${{ secrets.KEY }}" > private_key.pem
          chmod 600 private_key.pem
       
        

  deploy:
   runs-on: ubuntu-${{ env.IMAGE_TAG }}
   steps:
    - name: SSH to Server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }} 
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
               docker rm -f resume || true
               docker pull ${{ secrets.REGISTRY_USERNAME }}/docker-resume-a:${{ env.IMAGE_TAG }}
               docker run -d --name resume -p 8080:5001 ${{ secrets.REGISTRY_USERNAME }}/docker-resume-a:${{ env.IMAGE_TAG }}
