name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  
  build:
   
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: |
              docker build -t ${{secrets.REGISTRY_USERNAME}}/docker-resume-a:${{github.run_number}} .
              docker build -t ${{secrets.REGISTRY_USERNAME}}/docker-resume-a .
      - name: Push image 
        run: |
            docker login -u ${{secrets.REGISTRY_USERNAME}} -p ${{secrets.REGISTRY_PASS}}
            docker push ${{secrets.REGISTRY_USERNAME}}/docker-resume-a:${{github.run_number}}
            docker push ${{secrets.REGISTRY_USERNAME}}/docker-resume-a

      - name: Setup SSH
        run: |
          echo "${{ secrets.KEY }}" > private_key.pem
          chmod 600 private_key.pem
       
        

  deploy:
   runs-on: ubuntu-latest
   steps:
    - name: SSH to Server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }} 
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
                docker rm -f resume || true
                docker run -d --name resume -p 8080:5001 ${{ secrets.REGISTRY_USERNAME }}/docker-resume-a
